= Contribution guidelines

These guidelines instruct how to submit issues and contribute code or
documentation to the
https://github.com/whythoSanskar/TwitterBot[Twitter Bot]. If you notice a library or tool missing, there is hardly
any better way to contribute than creating your own project. 

These guidelines expect readers to have a basic knowledge about open
source as well as why and how to contribute to open source projects.

== Submitting issues

Bugs and enhancements are tracked in the
https://github.com/whythoSanskar/TwitterBot/issues[issue tracker].
If you are unsure if something is a bug or is a feature worth
implementing feel free to ask

Before submitting a new issue, it is always a good idea to check is the
same bug or enhancement already reported. If it is, please add your
comments to the existing issue instead of creating a new one.

=== Reporting bugs

Explain the bug you have encountered so that others can understand it
and preferably also reproduce it. Key things to have in good bug report:

. Version information
* Python interpreter version
* Operating system and its version

== Code contributions

If you have fixed a bug or implemented an enhancement, you can
contribute your changes via GitHub's pull requests. 

=== Choosing something to work on

Often you already have a bug or an enhancement you want to work on in
your mind, but you can also look at the link:[issue tracker] to find
bugs and enhancements submitted by others. The issues vary significantly
in complexity and difficulty, so you can try to find something that
matches your skill level and knowledge. There are two specific labels to
look for when looking for something to contribute:

https://github.com/whythoSanskar/TwitterBot/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

`good first issue`::
 
  These are generally easy to implement or fix. Thus these
  issues are especially good for new contributors.

=== Pull requests

On GitHub pull requests are the main mechanism to contribute code. They
are easy to use both for the contributor and for the person accepting
the contribution, and with more complex contributions it is easy also
for others to join the discussion. Preconditions for creating pull
requests are having a https://github.com/[GitHub account], installing
https://git-scm.com[Git].

GitHub has good articles explaining how to
https://help.github.com/articles/set-up-git/[set up Git],
https://help.github.com/articles/fork-a-repo/[fork a repository] and
https://help.github.com/articles/using-pull-requests[use pull requests]
and we do not go through them in more detail. We do, however, recommend
to create dedicated topic branches for pull requests instead of creating
them based on the master branch. This is especially important if you
plan to work on multiple pull requests at the same time.

==== General guidelines

All code, including test code, must be compatible with all supported
Python interpreters and versions. Most importantly this means that the
code must support Python.

==== Docstrings

Try adding docstrings to public APIs functions and the classes you create to improve code quality

=== Documentation

With new features adequate documentation is as important as the actual
functionality. Different documentation is needed depending on the issue.

=== Resolving conflicts

Conflicts can occur if there are new changes to the master that touch
the same code as your changes. In that case you should
`sync your fork` and `resolve conflicts` to allow for an easy merge.


==== For more info you can read `README.adoc`
